apiVersion: v1
kind: ServiceAccount
metadata:
  name: get-secret-sa
  namespace: default
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::160071257600:role/eksctl-my-web-server-addon-iamserviceaccount--Role1-WSwIovRUdIo5